### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by santosh9991** [graphql-python/graphene-sqlalchemy#115]
When I included schema in my application it throws the following error. Can any one help me debug this error. I am new to graphql. Any help is appreciated.

![image](https://user-images.githubusercontent.com/16803672/36619314-4615be40-18a3-11e8-98a4-201f76a8c52e.png)
Fig1: Error message

![image](https://user-images.githubusercontent.com/16803672/36619526-0d48c28c-18a4-11e8-803f-d90eef2637de.png)
Fig2: schema.py
![image](https://user-images.githubusercontent.com/16803672/36619542-20ae4b44-18a4-11e8-844a-5a31bcdea065.png)
Fig3: Models.py
![image](https://user-images.githubusercontent.com/16803672/36619579-359c9290-18a4-11e8-8d1d-dd75e2217236.png)
Fig4: app.py

**Comment by Tryph** [comment]
The line causing the error being `use_connection = any((issubclass(interface, Node) for interface in interfaces)`, there is a chance that the problem is from a wrong interface.

The traceback indicates that the error occurs from the line 8 of your `schema.py file`. This is where your `Customer` type is defined.

This `Customer` type actually declares interfaces: `interfaces = (relay.node, )`
But as far as I know, the relay module does not provide a `node` attribute. Instead it provides a `Node` class.

Uppercasing the 'n' of `relay.node` should fix your issue.

**Comment by santosh9991** [comment]
@Tryph : Thank you. It fixed my error.
