### ISSUE TITLE
Question About Long Running Mutations And Asynchronous Tasks

### ISSUE THREAD

**Issue by alexisrolland** [graphql-python/graphene-sqlalchemy#127]
Hello,

We're using Flask, Graphene and SQLAlchemy on our project. The API is currently executed on our server using uWSGI and Nginx. Some of the mutations we have created trigger long running jobs (like 2 to 5 minutes). We realized that:
- When one of the long running job is triggered / running, no other http request would be treated by our Flask application. Is this a known limitation from Graphene / SQLAlchemy? Or are we doing something wrong?
- What would you say is the best way to manage this kind of long running request from the end user point of view? I'm thinking about returning immediately a message saying the job is triggered and then let the job run in the background, but I'm not really sure how to manage such asynchronous task in Python.

Thank you
Alexis

**Comment by erikwrede** [comment]
Hey Alexis, 
sorry for the late reply. The problem is probably not relevant to you anymore. I'm still replying in case anyone else finds this issue looking for a solution.
`graphene 3.0` supports `async/await` using `asyncio`. Using that version of the library, long-running mutations can be converted to async mutations, and the long-running tasks they trigger can be moved to another thread that can be awaited (see https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor).

To use `graphene 3.0`, you also need to upgrade `graphene-sqlalchemy` to `3.0`. Since it is currently in beta, you need to explicitly specify the version as `3.0.0b1` or higher. Additionally, your webserver implementation needs to support asyncio, so you might need to switch to flask 2.0 or another asyncio-supporting server.
