### ISSUE TITLE
JSONString type in schema instead of int

### ISSUE THREAD

**Issue by comtihon** [graphql-python/graphene-sqlalchemy#159]
Hi, 
I have this id in my object:
`my_id = Column(BigInteger().with_variant(sqlite.INTEGER(), 'sqlite'), primary_key=True)`
But in graphql schema I see `JSONString` type instead of `Int`.
I use flask-sqlalchemy, graphene-sqlalchemy and flask-graphene.

Solution for now is to add `my_id = graphene.Int()` everywhere at `SQLAlchemyObjectType` subclasses. But I don't like it as I have to remember it.

Whitout `.with_variant(sqlite.INTEGER(), 'sqlite')` id type in schema becames `Float` which is also not correct.

**Comment by erikwrede** [comment]
I can not reproduce this with `graphene-sqlalchemy==3.0.0b1`. If this is still relevant, please open a new issue including a minimal example (SQLAlchemy Model + Graphene-SQLAlchemy types.)
However, I can reproduce that BigInteger is converted to the `graphene.Float` scalar instead of the `Integer` scalar. I have added this to the notes in #345.
