### ISSUE TITLE
Default type conversion for unknown types?

### ISSUE THREAD

**Issue by flewellyn** [graphql-python/graphene-sqlalchemy#176]
Is there a way to register a "default" handler for convert_sqlalchemy_type()?  I know about the use of the decorator's .register() method to register a new type, but the issue is that I want to be able to define a "catchall" for any unknown types that SQLAlchemy reflection may pick up.

I don't want to modify the base definition in graphene_sqlalchemy/converter.py, that would mean I would have to distribute a patched version of the library with my code.  Can I replace the base singledispatch method with a new base method, or would that break everything?

Failing that, where would I put the try/except block to catch unknown type errors, so I could just omit those columns?

**Comment by erikwrede** [comment]
Currently, there is no default converter. I think the default behavior is problematic since not every type is compatible with a default scalar such as `graphene.String`. Creating a custom converter exactly for the types you need seems to be the more favorable approach IMO. Even using SQA-Reflection, you should always know which types are present in your DB schema, so every need for additional type converters is predictable.
Patching the singledispatch method with something else would also work, since only this method is used to do the conversion interfacing.

 If you feel different about default conversion, feel free to post your specific use case in #345 and I'm open to discuss it!
