### ISSUE TITLE
Non-ORM Usage Examples

### ISSUE THREAD

**Issue by Julian** [graphql-python/graphene-sqlalchemy#19]
It would be useful to see a usage example that did not use the SQLAlchemy ORM layer.

**Comment by andreolaya** [comment]
@julian I'm looking for the same, I wonder if you already found something successfully?

**Comment by jnak** [comment]
I'm not sure what you mean in the context of this library. Can you elaborate?

**Comment by taybin** [comment]
@jnak Some of us use SQLAlchemy without using the ORM layer.  We prefer to just use the Core layer (https://docs.sqlalchemy.org/en/13/core/).  It would be helpful to see an example of how to do that.

**Comment by jnak** [comment]
This is not possible today since "graphene-sqlalchemy" currently heavily relies on the ORM layer to resolve queries. That said, it is mostly an implementation details from the perspective of application developers like you. 

We have a longer-term plan to offer the option to skip the ORM layer at some point but the motivation is to improve performance. It's not clear yet if this change will be visible to users of the library.

Closing for now since it is not possible.
