### ISSUE TITLE
Formatting datetime-like columns

### ISSUE THREAD

**Issue by thejcannon** [graphql-python/graphene-sqlalchemy#206]
It'd be nice to be able to specify a `strftime` string which would automatically be used when resolving datetime-like columns so the user gets a friendly value.

**Comment by jnak** [comment]
Please provide an example of what the API would look like.

**Comment by thejcannon** [comment]
Probably using the `Meta` options:
```py
class Book(SQLAlchemyObjectType):
   class Meta:
      model = models.Book
      time_format = '%a, %d %b %Y %H:%M:%S'
```

**Comment by erikwrede** [comment]
Sounds helpful! However, I don't think a `Meta` entry would be the right place for this since some models might require different time formats in the same response. 
The approach should allow field-level adjustments, but an additional default global option is also handy. I'm open to more suggestions.

**Comment by erikwrede** [comment]
Closing this as part of triage, since this is an issue that is easily solvable in the frontend, as mentioned above. Please open a new issue with compelling examples, if you need this feature.
