### ISSUE TITLE
Model vs Node in naming in docs and tests

### ISSUE THREAD

**Issue by 13rac1** [graphql-python/graphene-sqlalchemy#33]
The documentation and example code use: Example and ExampleModel.

https://github.com/graphql-python/graphene-sqlalchemy/blob/08fcfc0b2548cd3519e4b19772acda4495089392/docs/tutorial.rst#schema

```python
from models import db_session, Department as DepartmentModel, Employee as EmployeeModel

class Department(SQLAlchemyObjectType):
    class Meta:
        model = DepartmentModel
        interfaces = (relay.Node, )
```

The unit tests use the opposite naming convention: ExampleNode and Example.

https://github.com/graphql-python/graphene-sqlalchemy/blob/08fcfc0b2548cd3519e4b19772acda4495089392/graphene_sqlalchemy/tests/test_query.py#L10

```python
from .models import Article, Base, Editor, Reporter

    class ArticleNode(SQLAlchemyObjectType):

        class Meta:
            model = Article
            interfaces = (Node, )
```

Which is "correct"?

**Comment by paridin** [comment]
both are correct, the only difference is the import statement.

[tutorial.rst](https://github.com/graphql-python/graphene-sqlalchemy/blob/08fcfc0b2548cd3519e4b19772acda4495089392/docs/tutorial.rst#schema)

`from graphene import relay`

[test_query.py](https://github.com/graphql-python/graphene-sqlalchemy/blob/08fcfc0b2548cd3519e4b19772acda4495089392/graphene_sqlalchemy/tests/test_query.py#L6)

`from graphene.relay import Node`

**Comment by eosrei** [comment]
Both work, but only one is "correct." The question is which? There should be only one recommendation.

**Comment by paridin** [comment]
It depends, To me, the second one is better since it's simple to remember you need a Node instance, and in this case, you only have a `relay.Node` instance but maybe you want to implement a custom behavior and you create a new `class Node` so you only need to change the import statement, one of the pros you only import the class Node.

For others, the first is better since `Namespaces are one honking great idea`, so when you read your code again you can see what kind of Node instance is, then it helps to omit to go to the import section since it's more readable, the con is you are importing the whole module but you only use one class of that package and this approach is more acceptable for standard libraries than custom.

So not only one is "correct", both are, think about what is better for you. and use that style.

If you want to clarify what is your style [import statements](https://www.python.org/dev/peps/pep-0008/#imports) section from pep8 can help you.
