### ISSUE TITLE
No UUIDType support

### ISSUE THREAD

**Issue by calibodhi** [graphql-python/graphene-sqlalchemy#336]
Almost identical to #257 
Opening a new issue since I could not find a solution. Any help is much appreciated.

```python

from sqlalchemy_utils import UUIDType

class Item(Base):
    id = Column(binary=False, native=True), primary_key=True, default=uuid4)

from graphene_sqlalchemy import SQLAlchemyObjectType

class ItemNode(SQLAlchemyObjectType):
    class Meta:
        model = Item
```

```
Exception: Don't know how to convert the SQLAlchemy field item.id (<class 'sqlalchemy.sql.schema.Column'>)
```

How can I support UUIDs?

**Comment by calibodhi** [comment]
@erikwrede thanks! It works with the postgres UUID on a postgres db. I would love to get this working with sqlite3. I will open a separate issue for that, if needed, and change the name back on this since I referenced the other issues.

```
from uuid import uuid4
from sqlalchemy.dialects.postgresql import UUID

class Item(Base):
   id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)

from graphene_sqlalchemy import SQLAlchemyObjectType

class ItemNode(SQLAlchemyObjectType):
    class Meta:
        model = Item
```

**Comment by erikwrede** [comment]
Sorry for the late reply. I haven't found the time to do any testing earlier.  Since you referenced #257, I expected that you already tried adding a custom type converter for `UUIDType`. This is necessary because SQLAlchemy does not natively support `sqlalchemy_utils.UUIDType` and does not know how to convert this time into a Graphene-Type for the GraphQL-Schema.
You are seeing the error Message `Exception: Don't know how to convert the SQLAlchemy field item.id (<class 'sqlalchemy.sql.schema.Column'>)` because of that.

Adding a custom type converter is as simple as adding these lines to your code before the model:

```python
from sqlalchemy_utils import UUIDType
from graphene_sqlalchemy.converter import convert_sqlalchemy_type
@convert_sqlalchemy_type.register(UUIDType)
def convert_column_to_string(type, column, registry=None):
    return graphene.String
```

This is essentially the solution detailed in #257. I've just tested this with your code above on `graphene-sqlalchemy==3.0.0b1` and verified that it works! 
I could not reproduce any of the other problems mentioned in #257. Try it out and let me know if it worked!
